// <auto-generated />
using CineWave.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CineWave.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240519193124_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CineWave.Models.Campanha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeRange")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Faxa_Etaria");

                    b.Property<float>("Budget")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("Budget");

                    b.Property<string>("GenderMovie")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Genero_Filme");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Titulo_Filme");

                    b.Property<int>("ReachExpectations")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Expectativa_De_Alcance");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("T_CNWV_CAMPANHA");
                });

            modelBuilder.Entity("CineWave.Models.Insights", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("AverageCostPerClick")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("Custo_Medio_Click");

                    b.Property<int>("ConversionPrediction")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Previsao_De_Conversao");

                    b.Property<string>("MarketingChannel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Canal_De_Marketing");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Titulo_Filme");

                    b.Property<int>("RoiForecast")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Previsao_De_Roi");

                    b.HasKey("Id");

                    b.ToTable("T_CNWV_INSIGHTS");
                });

            modelBuilder.Entity("CineWave.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("Usuario_Ativo");

                    b.Property<string>("PassWordHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Hash_Senha");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Email_Usuario");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Nome_Usuario");

                    b.HasKey("Id");

                    b.ToTable("T_CNWV_USUARIO");
                });

            modelBuilder.Entity("CineWave.Models.Campanha", b =>
                {
                    b.HasOne("CineWave.Models.Usuario", "Usuario")
                        .WithMany("Campanhas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CineWave.Models.Usuario", b =>
                {
                    b.Navigation("Campanhas");
                });
#pragma warning restore 612, 618
        }
    }
}
